const themeToggleButton=document.getElementById('themeToggle')
const ctaButton=document.getElementById('ctaButton')
const hamburger=document.querySelector('.hamburger')
const navMenu=document.querySelector('.nav-menu')
const navLinks=document.querySelectorAll('.nav-links')
const serviceCards=document.querySelectorAll('.service-card')